spring/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from restaurants.views import menu
urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
	url(r'^menu/$',menu),
	url(r'^$', 'spring.views.home', name='home'),
]

restaurants/models.py
#from __future__ import unicode_literals

from django.db import models


class Restaurant(models.Model):
    name = models.CharField(max_length=20)
    phone_number = models.CharField(max_length=15)
    address = models.CharField(max_length=50, blank=True)

    def __str__(self):
        """
        :returns: name string
        """
        return self.name


class Food(models.Model):
    name = models.CharField(max_length=20)
    price = models.DecimalField(max_digits=3, decimal_places=0)
    comment = models.CharField(max_length=50, blank=True)
    is_spicy = models.BooleanField(default=False)
    restaurant = models.ForeignKey(Restaurant)

    def __str__(self):
        """
        :returns: name string
        """
        return self.name

    class Meta:

        """Meta: attribute, options"""

        ordering = ['price']

restaurants/views.py
from django.shortcuts import render_to_response

from restaurants.models import Restaurant


def menu(request):
    """retrun a menu response
    :request: client request
    :returns: http response
    """
    restaurants = Restaurant.objects.all()
    return render_to_response('menu.html', locals())

spring/views.py
 
from django.shortcuts import render_to_response
#from django import template



def home(request):
        return render_to_response('home.html', locals())

restaurants/templates/home.html
<!doctype html>
<html>
    <head>
        <title> Restaurant King </title>
        <meta charset='utf-8'>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">
        <style>
        th { text-align: center; }
        div.center_padding {
            text-align: center;
            padding: 128px 15px;
        }
        </style>
    </head>
    <body>

        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                   
                </div>
                <!--div id="navbar" class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="#">Home</a></li>
                        <li><a href="#about">About</a></li>
                        <li><a href="#contact">Contact</a></li>
                    </ul>
                </div--><!--/.nav-collapse -->
            </div>
        </nav>

        <div class="container">
            <div class="center_padding">
                <h2>歡迎來到餐廳王</h2>
                
                <p><a href="/menu/">餐廳列表</a></p>
               
                <p><a href="/admin/">後台登入</a></p>
                
            </div>
        </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    </body>
</html>

restaurants/templates/menu.html
<!doctype html>
<html>
    <head>
        <title> Menu </title>
        <meta charset='utf-8'>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">
        <style>
        th { text-align: center; }
        div.menus {
            text-align: center;
            padding: 40px 15px;
        }
        </style>
    </head>
    <body>

        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                
                </div>
                <!--div id="navbar" class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="#">Home</a></li>
                        <li><a href="#about">About</a></li>
                        <li><a href="#contact">Contact</a></li>
                    </ul>
                </div--><!--/.nav-collapse -->
            </div>
        </nav>

        <div class="container">
            <div class="menus">
                <p>
                {% for r in restaurants %}
                <h2>{{ r.name }}</h2>
                {% if r.food_set.all %}
                <p>本餐廳共有{{ r.food_set.all|length }}道菜</p>
                <table class="table">
                    <tr>
                        <th>菜名</th>
                        <th>價格</th>
                        <th>辣不辣</th>
                        <th>註解</th>
                    </tr>
                    {% for food in r.food_set.all %}
                    <tr>
                        <td> {{ food.name }} </td>
                        <td> {{ food.price }} </td>
                        <td> {% if food.is_spicy %} 辣 {% else %} 不辣 {% endif %} </td>
                        <td> {{ food.comment }} </td>
                    </tr>
                    {% endfor %}
                </table>
                </p>
                {% else %}
                <p>本餐廳啥都沒賣</p>
                {% endif %}
                {% endfor %}
            </div>
        </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    </body>
</html>